# Generated by Django 4.0.6 on 2022-08-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='my_class',
        ),
    ]
