# Generated by Django 4.0.6 on 2022-08-24 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_statuses', '0001_initial'),
        ('task_manager', '0004_labels_tasklabels_tasks_tasklabels_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_status', to='app_statuses.statuses'),
        ),
        migrations.DeleteModel(
            name='Statuses',
        ),
    ]
