# Generated by Django 4.0.6 on 2022-08-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_alter_tasks_status_delete_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklabels',
            name='label',
        ),
        migrations.RemoveField(
            model_name='tasklabels',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='status',
        ),
        migrations.DeleteModel(
            name='Labels',
        ),
        migrations.DeleteModel(
            name='TaskLabels',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
