# Generated by Django 4.1 on 2022-08-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_remove_tasklabels_label_remove_tasklabels_task_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
