# Generated by Django 4.1.1 on 2022-09-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labels',
            options={},
        ),
        migrations.AlterField(
            model_name='labels',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
