# Generated by Django 4.1.1 on 2022-09-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={},
        ),
    ]
