name: make-lint
on: push
jobs:
  make-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Step 1
      run: |
        pip install poetry
        poetry add flake8
        make lint
